version: '3'
services:

  zookeeper:
    image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
    hostname: "zookeeper"
    restart: on-failure
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  mesos-master:
    image: newsupapat/mesos-master:1.9.0
    hostname: "mesos-master"
    container_name: master
    privileged: true
    restart: on-failure
    volumes:
      - "/log/mesos:/var/log/mesos"
      - "/tmp/mesos:/var/tmp/mesos"
    environment:
      - MESOS_HOSTNAME=3.0.176.188
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
      - MESOS_WORK_DIR=/var/tmp/mesos
    links:
      - zookeeper
    ports:
      - "5050:5050"

  mesos-slave:
    image: newsupapat/mesos-slave:1.9.0
    hostname: "mesos-slave"
    container_name: slave
    restart: on-failure
    privileged: true
    environment:
      - MESOS_HOSTNAME=3.0.176.188
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    links:
      - zookeeper
      - mesos-master
    ports:
      - "5151:5151"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup
      - "/log/mesos-agent:/var/log/mesos"
      - "/tmp/mesos-agent:/var/tmp/mesos" 
  marathon:
    image: datastrophic/marathon:1.3.6
    hostname: "marathon"
    container_name: marathon
    restart: on-failure
    environment:
      - MARATHON_HOSTNAME=3.0.176.188
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/marathon
    links:
      - zookeeper
      - mesos-master
    ports:
      - "8080:8080"

  chronos:
    image: datastrophic/chronos:mesos-1.1.0-chronos-3.0.1
    hostname: "chronos"
    container_name: chronos
    restart: on-failure
    environment:
      - CHRONOS_HOSTNAME=3.0.176.188
      - CHRONOS_HTTP_PORT=4400
      - CHRONOS_MASTER=zk://zookeeper:2181/mesos
      - CHRONOS_ZK_HOSTS=zookeeper:2181
    links:
      - zookeeper
      - mesos-master
    ports:
      - "4400:4400"
  # cassandra:
  #   image: cassandra:3.3
  #   hostname: "cassandra"
  #   ports:
  #     - "9160:9160"
  #     - "9042:9042"
